# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [cent-os]

    steps:
    - uses: actions/checkout@v2
    - name: Run Hello World
      run: echo "Hello World" 
    #- name: Set up JDK 1.8
    #  uses: actions/setup-java@v1
    #  with:
    #    java-version: 1.8
    #- name: Package with Maven
    #  run: mvn package
    #- name: Deploy Package to registry
    #  run: mvn deploy
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
